export enum OrderStatus {
  PLACED = 'PLACED',
  APPROVED = 'APPROVED',
  DELAYED = 'DELAYED',
  READY_FOR_SHIPPING = 'READY',
  SHIPPED = 'SHIPPED',
  DISPATCHED = 'DISPATCHED',
  DISPUTE = 'DISPUTE',
  CLOSED = 'CLOSED',
}